baseURL = "https://aws-101.devopsart.dev/"
title = "AWS 101 documentation"
theme = "learn"
defaultContentLanguage="ko"
relativeURLs=true
canonifyURLs=false

# Will give values to .Lastmod etc.
enableGitInfo = true

[params]
  description = "AWS 101 with DevopsArt"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableLanguageSwitchingButton = true
  disableShortcutsTitle=false
  disableInlineCopyToClipBoard = true


## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
hrefTargetBlank = true
